spring:
  application:
    name: hub-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: ${CLOUD_SERVICE_ID}
    openfeign:
      client:
        config:
          default: # 모든 클라이언트에 적용
            connectTimeout: 5000 # 연결 시도(소켓 연결) 타임아웃: 밀리초 단위. 5000ms = 5초
            readTimeout: 5000 # 서버 응답을 기다리는 읽기 타임아웃:
            loggerLevel: full # 로거 레벨: NONE, BASIC, HEADERS, FULL 중 하나.
  docker:
    compose:
      lifecycle-management: start_only
eureka:
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_HOSTNAME}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

rabbit:
  hub:
    exchange: hub.exchange
    queue: hub.queue
    routing-key: hub.#